// generated by tscfg 0.8.0 on Thu Apr 20 16:57:17 PDT 2017
// source: etc/config/config.conf

package com.sudothought.common;

public class ConfigVals {
  public final ConfigVals.Agent agent;
  public final ConfigVals.Proxy proxy;
  public ConfigVals(com.typesafe.config.Config c) {
    this.agent = new ConfigVals.Agent(c.getConfig("agent"));
    this.proxy = new ConfigVals.Proxy(c.getConfig("proxy"));
  }

  public static class Agent {
    public final Agent.Grpc                            grpc;
    public final Agent.Internal                        internal;
    public final Agent.Metrics                         metrics;
    public final java.lang.String                      name;
    public final java.util.List<Agent.PathConfigs$Elm> pathConfigs;
    public final Agent.Zipkin                          zipkin;
    public Agent(com.typesafe.config.Config c) {
      this.grpc = new Agent.Grpc(c.getConfig("grpc"));
      this.internal = new Agent.Internal(c.getConfig("internal"));
      this.metrics = new Agent.Metrics(c.getConfig("metrics"));
      this.name = c.hasPathOrNull("name") ? c.getString("name") : "";
      this.pathConfigs = $_LAgent_PathConfigs$Elm(c.getList("pathConfigs"));
      this.zipkin = new Agent.Zipkin(c.getConfig("zipkin"));
    }

    private static java.util.List<Agent.PathConfigs$Elm> $_LAgent_PathConfigs$Elm(com.typesafe.config.ConfigList cl) {
      java.util.ArrayList<Agent.PathConfigs$Elm> al = new java.util.ArrayList<>();
      for (com.typesafe.config.ConfigValue cv : cl) {
        al.add(new Agent.PathConfigs$Elm(((com.typesafe.config.ConfigObject) cv).toConfig()));
      }
      return java.util.Collections.unmodifiableList(al);
    }

    public static class Grpc {
      public final boolean          allMetricsReported;
      public final java.lang.String hostname;
      public final boolean          metricsEnabled;
      public final int              port;
      public final int              reconectPauseSecs;
      public final boolean          zipkinReportingEnabled;

      public Grpc(com.typesafe.config.Config c) {
        this.allMetricsReported = c.hasPathOrNull("allMetricsReported") && c.getBoolean("allMetricsReported");
        this.hostname = c.hasPathOrNull("hostname") ? c.getString("hostname") : "localhost";
        this.metricsEnabled = c.hasPathOrNull("metricsEnabled") && c.getBoolean("metricsEnabled");
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 50051;
        this.reconectPauseSecs = c.hasPathOrNull("reconectPauseSecs") ? c.getInt("reconectPauseSecs") : 3;
        this.zipkinReportingEnabled = !c.hasPathOrNull("zipkinReportingEnabled") || c.getBoolean("zipkinReportingEnabled");
      }
    }

    public static class Internal {
      public final boolean heartbeatEnabled;
      public final int     heartbeatMaxInactivitySecs;
      public final int     scrapeQueueSize;

      public Internal(com.typesafe.config.Config c) {
        this.heartbeatEnabled = !c.hasPathOrNull("heartbeatEnabled") || c.getBoolean("heartbeatEnabled");
        this.heartbeatMaxInactivitySecs = c.hasPathOrNull("heartbeatMaxInactivitySecs") ? c.getInt("heartbeatMaxInactivitySecs") : 5;
        this.scrapeQueueSize = c.hasPathOrNull("scrapeQueueSize") ? c.getInt("scrapeQueueSize") : 128;
      }
    }

    public static class Metrics {
      public final boolean          classLoadingExportsEnabled;
      public final boolean          enabled;
      public final boolean          garbageCollectorExportsEnabled;
      public final boolean          memoryPoolsExportsEnabled;
      public final java.lang.String path;
      public final int              port;
      public final boolean          standardExportsEnabled;
      public final boolean          threadExportsEnabled;
      public final boolean          versionInfoExportsEnabled;

      public Metrics(com.typesafe.config.Config c) {
        this.classLoadingExportsEnabled = c.hasPathOrNull("classLoadingExportsEnabled") && c.getBoolean("classLoadingExportsEnabled");
        this.enabled = !c.hasPathOrNull("enabled") || c.getBoolean("enabled");
        this.garbageCollectorExportsEnabled = c.hasPathOrNull("garbageCollectorExportsEnabled") && c.getBoolean("garbageCollectorExportsEnabled");
        this.memoryPoolsExportsEnabled = c.hasPathOrNull("memoryPoolsExportsEnabled") && c.getBoolean("memoryPoolsExportsEnabled");
        this.path = c.hasPathOrNull("path") ? c.getString("path") : "metrics";
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 8083;
        this.standardExportsEnabled = c.hasPathOrNull("standardExportsEnabled") && c.getBoolean("standardExportsEnabled");
        this.threadExportsEnabled = c.hasPathOrNull("threadExportsEnabled") && c.getBoolean("threadExportsEnabled");
        this.versionInfoExportsEnabled = c.hasPathOrNull("versionInfoExportsEnabled") && c.getBoolean("versionInfoExportsEnabled");
      }
    }

    public static class PathConfigs$Elm {
      public final java.lang.String name;
      public final java.lang.String path;
      public final java.lang.String url;

      public PathConfigs$Elm(com.typesafe.config.Config c) {
        this.name = c.getString("name");
        this.path = c.getString("path");
        this.url = c.getString("url");
      }
    }

    public static class Zipkin {
      public final boolean          enabled;
      public final java.lang.String hostname;
      public final java.lang.String path;
      public final int              port;
      public final java.lang.String serviceName;

      public Zipkin(com.typesafe.config.Config c) {
        this.enabled = c.hasPathOrNull("enabled") && c.getBoolean("enabled");
        this.hostname = c.hasPathOrNull("hostname") ? c.getString("hostname") : "localhost";
        this.path = c.hasPathOrNull("path") ? c.getString("path") : "api/v1/spans";
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 9411;
        this.serviceName = c.hasPathOrNull("serviceName") ? c.getString("serviceName") : "prometheus-agent";
      }
    }
  }

  public static class Proxy {
    public final Proxy.Grpc2     grpc;
    public final Proxy.Http      http;
    public final Proxy.Internal2 internal;
    public final Proxy.Metrics2  metrics;
    public final Proxy.Zipkin2   zipkin;
    public Proxy(com.typesafe.config.Config c) {
      this.grpc = new Proxy.Grpc2(c.getConfig("grpc"));
      this.http = new Proxy.Http(c.getConfig("http"));
      this.internal = new Proxy.Internal2(c.getConfig("internal"));
      this.metrics = new Proxy.Metrics2(c.getConfig("metrics"));
      this.zipkin = new Proxy.Zipkin2(c.getConfig("zipkin"));
    }

    public static class Grpc2 {
      public final boolean allMetricsReported;
      public final boolean metricsEnabled;
      public final int     port;
      public final boolean zipkinReportingEnabled;

      public Grpc2(com.typesafe.config.Config c) {
        this.allMetricsReported = c.hasPathOrNull("allMetricsReported") && c.getBoolean("allMetricsReported");
        this.metricsEnabled = c.hasPathOrNull("metricsEnabled") && c.getBoolean("metricsEnabled");
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 50051;
        this.zipkinReportingEnabled = !c.hasPathOrNull("zipkinReportingEnabled") || c.getBoolean("zipkinReportingEnabled");
      }
    }

    public static class Http {
      public final int port;

      public Http(com.typesafe.config.Config c) {
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 8080;
      }
    }

    public static class Internal2 {
      public final int     maxAgentInactivitySecs;
      public final int     requestTimeoutSecs;
      public final int     scrapeQueueSize;
      public final boolean staleAgentCheckEnabled;
      public final int     staleAgentCheckPauseSecs;

      public Internal2(com.typesafe.config.Config c) {
        this.maxAgentInactivitySecs = c.hasPathOrNull("maxAgentInactivitySecs") ? c.getInt("maxAgentInactivitySecs") : 15;
        this.requestTimeoutSecs = c.hasPathOrNull("requestTimeoutSecs") ? c.getInt("requestTimeoutSecs") : 5;
        this.scrapeQueueSize = c.hasPathOrNull("scrapeQueueSize") ? c.getInt("scrapeQueueSize") : 128;
        this.staleAgentCheckEnabled = !c.hasPathOrNull("staleAgentCheckEnabled") || c.getBoolean("staleAgentCheckEnabled");
        this.staleAgentCheckPauseSecs = c.hasPathOrNull("staleAgentCheckPauseSecs") ? c.getInt("staleAgentCheckPauseSecs") : 10;
      }
    }

    public static class Metrics2 {
      public final boolean          classLoadingExportsEnabled;
      public final boolean          enabled;
      public final boolean          garbageCollectorExportsEnabled;
      public final boolean          memoryPoolsExportsEnabled;
      public final java.lang.String path;
      public final int              port;
      public final boolean          standardExportsEnabled;
      public final boolean          threadExportsEnabled;
      public final boolean          versionInfoExportsEnabled;

      public Metrics2(com.typesafe.config.Config c) {
        this.classLoadingExportsEnabled = c.hasPathOrNull("classLoadingExportsEnabled") && c.getBoolean("classLoadingExportsEnabled");
        this.enabled = !c.hasPathOrNull("enabled") || c.getBoolean("enabled");
        this.garbageCollectorExportsEnabled = c.hasPathOrNull("garbageCollectorExportsEnabled") && c.getBoolean("garbageCollectorExportsEnabled");
        this.memoryPoolsExportsEnabled = c.hasPathOrNull("memoryPoolsExportsEnabled") && c.getBoolean("memoryPoolsExportsEnabled");
        this.path = c.hasPathOrNull("path") ? c.getString("path") : "metrics";
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 8082;
        this.standardExportsEnabled = c.hasPathOrNull("standardExportsEnabled") && c.getBoolean("standardExportsEnabled");
        this.threadExportsEnabled = c.hasPathOrNull("threadExportsEnabled") && c.getBoolean("threadExportsEnabled");
        this.versionInfoExportsEnabled = c.hasPathOrNull("versionInfoExportsEnabled") && c.getBoolean("versionInfoExportsEnabled");
      }
    }

    public static class Zipkin2 {
      public final boolean          enabled;
      public final java.lang.String hostname;
      public final java.lang.String path;
      public final int              port;
      public final java.lang.String serviceName;

      public Zipkin2(com.typesafe.config.Config c) {
        this.enabled = c.hasPathOrNull("enabled") && c.getBoolean("enabled");
        this.hostname = c.hasPathOrNull("hostname") ? c.getString("hostname") : "localhost";
        this.path = c.hasPathOrNull("path") ? c.getString("path") : "api/v1/spans";
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 9411;
        this.serviceName = c.hasPathOrNull("serviceName") ? c.getString("serviceName") : "prometheus-proxy";
      }
    }
  }
}
      
