// generated by tscfg 0.8.0 on Tue Apr 18 12:56:00 PDT 2017
// source: etc/config/config.conf

package com.sudothought.common;

public class ConfigVals {
  public final ConfigVals.Agent  agent;
  public final ConfigVals.Proxy2 proxy;
  public ConfigVals(com.typesafe.config.Config c) {
    this.agent = new ConfigVals.Agent(c.getConfig("agent"));
    this.proxy = new ConfigVals.Proxy2(c.getConfig("proxy"));
  }

  public static class Agent {
    public final Agent.Metrics                         metrics;
    public final java.util.List<Agent.PathConfigs$Elm> pathConfigs;
    public final Agent.Prometheus                      prometheus;
    public final Agent.Proxy                           proxy;
    public final Agent.Scrape                          scrape;
    public final Agent.Zipkin                          zipkin;
    public Agent(com.typesafe.config.Config c) {
      this.metrics = new Agent.Metrics(c.getConfig("metrics"));
      this.pathConfigs = $_LAgent_PathConfigs$Elm(c.getList("pathConfigs"));
      this.prometheus = new Agent.Prometheus(c.getConfig("prometheus"));
      this.proxy = new Agent.Proxy(c.getConfig("proxy"));
      this.scrape = new Agent.Scrape(c.getConfig("scrape"));
      this.zipkin = new Agent.Zipkin(c.getConfig("zipkin"));
    }

    private static java.util.List<Agent.PathConfigs$Elm> $_LAgent_PathConfigs$Elm(com.typesafe.config.ConfigList cl) {
      java.util.ArrayList<Agent.PathConfigs$Elm> al = new java.util.ArrayList<>();
      for (com.typesafe.config.ConfigValue cv : cl) {
        al.add(new Agent.PathConfigs$Elm(((com.typesafe.config.ConfigObject) cv).toConfig()));
      }
      return java.util.Collections.unmodifiableList(al);
    }

    public static class Metrics {
      public final boolean          enabled;
      public final java.lang.String path;
      public final int              port;

      public Metrics(com.typesafe.config.Config c) {
        this.enabled = !c.hasPathOrNull("enabled") || c.getBoolean("enabled");
        this.path = c.hasPathOrNull("path") ? c.getString("path") : "metrics";
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 8083;
      }
    }

    public static class PathConfigs$Elm {
      public final java.lang.String name;
      public final java.lang.String path;
      public final java.lang.String url;

      public PathConfigs$Elm(com.typesafe.config.Config c) {
        this.name = c.getString("name");
        this.path = c.getString("path");
        this.url = c.getString("url");
      }
    }

    public static class Prometheus {
      public final boolean allMetrics;
      public final boolean enabled;

      public Prometheus(com.typesafe.config.Config c) {
        this.allMetrics = !c.hasPathOrNull("allMetrics") || c.getBoolean("allMetrics");
        this.enabled = !c.hasPathOrNull("enabled") || c.getBoolean("enabled");
      }
    }

    public static class Proxy {
      public final java.lang.String hostname;
      public final int              port;
      public final int              reconectPauseSecs;

      public Proxy(com.typesafe.config.Config c) {
        this.hostname = c.hasPathOrNull("hostname") ? c.getString("hostname") : "localhost";
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 50051;
        this.reconectPauseSecs = c.hasPathOrNull("reconectPauseSecs") ? c.getInt("reconectPauseSecs") : 3;
      }
    }

    public static class Scrape {
      public final boolean metricsEnabled;
      public final int     queueSize;

      public Scrape(com.typesafe.config.Config c) {
        this.metricsEnabled = !c.hasPathOrNull("metricsEnabled") || c.getBoolean("metricsEnabled");
        this.queueSize = c.hasPathOrNull("queueSize") ? c.getInt("queueSize") : 128;
      }
    }

    public static class Zipkin {
      public final boolean          enabled;
      public final java.lang.String hostname;
      public final java.lang.String path;
      public final int              port;
      public final java.lang.String serviceName;

      public Zipkin(com.typesafe.config.Config c) {
        this.enabled = c.hasPathOrNull("enabled") && c.getBoolean("enabled");
        this.hostname = c.hasPathOrNull("hostname") ? c.getString("hostname") : "localhost";
        this.path = c.hasPathOrNull("path") ? c.getString("path") : "api/v1/spans";
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 9411;
        this.serviceName = c.hasPathOrNull("serviceName") ? c.getString("serviceName") : "prometheus-agent";
      }
    }
  }

  public static class Proxy2 {
    public final Proxy2.Grpc        grpc;
    public final Proxy2.Http        http;
    public final Proxy2.Metrics2    metrics;
    public final Proxy2.Prometheus2 prometheus;
    public final Proxy2.Zipkin2     zipkin;
    public Proxy2(com.typesafe.config.Config c) {
      this.grpc = new Proxy2.Grpc(c.getConfig("grpc"));
      this.http = new Proxy2.Http(c.getConfig("http"));
      this.metrics = new Proxy2.Metrics2(c.getConfig("metrics"));
      this.prometheus = new Proxy2.Prometheus2(c.getConfig("prometheus"));
      this.zipkin = new Proxy2.Zipkin2(c.getConfig("zipkin"));
    }

    public static class Grpc {
      public final int port;

      public Grpc(com.typesafe.config.Config c) {
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 50051;
      }
    }

    public static class Http {
      public final int port;

      public Http(com.typesafe.config.Config c) {
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 8080;
      }
    }

    public static class Metrics2 {
      public final boolean          enabled;
      public final java.lang.String path;
      public final int              port;

      public Metrics2(com.typesafe.config.Config c) {
        this.enabled = !c.hasPathOrNull("enabled") || c.getBoolean("enabled");
        this.path = c.hasPathOrNull("path") ? c.getString("path") : "metrics";
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 8082;
      }
    }

    public static class Prometheus2 {
      public final boolean allMetrics;
      public final boolean enabled;

      public Prometheus2(com.typesafe.config.Config c) {
        this.allMetrics = !c.hasPathOrNull("allMetrics") || c.getBoolean("allMetrics");
        this.enabled = !c.hasPathOrNull("enabled") || c.getBoolean("enabled");
      }
    }

    public static class Zipkin2 {
      public final boolean          enabled;
      public final java.lang.String hostname;
      public final java.lang.String path;
      public final int              port;
      public final java.lang.String serviceName;

      public Zipkin2(com.typesafe.config.Config c) {
        this.enabled = c.hasPathOrNull("enabled") && c.getBoolean("enabled");
        this.hostname = c.hasPathOrNull("hostname") ? c.getString("hostname") : "localhost";
        this.path = c.hasPathOrNull("path") ? c.getString("path") : "api/v1/spans";
        this.port = c.hasPathOrNull("port") ? c.getInt("port") : 9411;
        this.serviceName = c.hasPathOrNull("serviceName") ? c.getString("serviceName") : "prometheus-proxy";
      }
    }
  }
}
      
