codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true

ignore:
  - "src/main/java/io/prometheus/common/ConfigVals.java"
  - "build/generated/**"

comment:
  layout: "diff, flags, files, footer"
  behavior: default
  require_changes: true

flags:
  unittests:
    paths:
      - src/main/
    carryforward: true
