{{- if and .Values.service.enabled .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
  labels:
    {{- include "prometheus-agent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "prometheus-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
{{- end }}
