agent {
//  proxy.hostname = "localhost"

  proxy {
    endpoints = [ "localhost:50051", "localhost:50052" ]
  }

  pathConfigs: [
    {
      name: "My App metrics"
      path: my_app_metrics2
      url: "http://localhost:9102/metrics"
    }
  ]
}
