# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!import grpc

import proto.proxy_service_pb2 as proto_dot_proxy__service__pb2


class ProxyServiceStub(object):
    def __init__(self, channel):
        """Constructor.
    
        Args:
          channel: A grpc.Channel.
        """
        self.registerAgent = channel.unary_unary(
            '/proxy_service.ProxyService/registerAgent',
            request_serializer=proto_dot_proxy__service__pb2.RegisterRequest.SerializeToString,
            response_deserializer=proto_dot_proxy__service__pb2.RegisterResponse.FromString,
        )
        self.getMetrics = channel.stream_stream(
            '/proxy_service.ProxyService/getMetrics',
            request_serializer=proto_dot_proxy__service__pb2.RequestMsg.SerializeToString,
            response_deserializer=proto_dot_proxy__service__pb2.ResponseMsg.FromString,
        )


class ProxyServiceServicer(object):
    def registerAgent(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMetrics(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'registerAgent': grpc.unary_unary_rpc_method_handler(
            servicer.registerAgent,
            request_deserializer=proto_dot_proxy__service__pb2.RegisterRequest.FromString,
            response_serializer=proto_dot_proxy__service__pb2.RegisterResponse.SerializeToString,
        ),
        'getMetrics': grpc.stream_stream_rpc_method_handler(
            servicer.getMetrics,
            request_deserializer=proto_dot_proxy__service__pb2.RequestMsg.FromString,
            response_serializer=proto_dot_proxy__service__pb2.ResponseMsg.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'proxy_service.ProxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
