# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!import grpc

import proto.proxy_service_pb2 as proto_dot_proxy__service__pb2


class ProxyServiceStub(object):
    def __init__(self, channel):
        """Constructor.
    
        Args:
          channel: A grpc.Channel.
        """
        self.registerAgent = channel.unary_unary(
            '/proxy_service.ProxyService/registerAgent',
            request_serializer=proto_dot_proxy__service__pb2.RegisterRequest.SerializeToString,
            response_deserializer=proto_dot_proxy__service__pb2.RegisterResponse.FromString,
        )
        self.readRequests = channel.unary_stream(
            '/proxy_service.ProxyService/readRequests',
            request_serializer=proto_dot_proxy__service__pb2.AgentInfo.SerializeToString,
            response_deserializer=proto_dot_proxy__service__pb2.ScrapeRequest.FromString,
        )
        self.writeResponses = channel.stream_unary(
            '/proxy_service.ProxyService/writeResponses',
            request_serializer=proto_dot_proxy__service__pb2.ScrapeResult.SerializeToString,
            response_deserializer=proto_dot_proxy__service__pb2.Empty.FromString,
        )


class ProxyServiceServicer(object):
    def registerAgent(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readRequests(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def writeResponses(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'registerAgent': grpc.unary_unary_rpc_method_handler(
            servicer.registerAgent,
            request_deserializer=proto_dot_proxy__service__pb2.RegisterRequest.FromString,
            response_serializer=proto_dot_proxy__service__pb2.RegisterResponse.SerializeToString,
        ),
        'readRequests': grpc.unary_stream_rpc_method_handler(
            servicer.readRequests,
            request_deserializer=proto_dot_proxy__service__pb2.AgentInfo.FromString,
            response_serializer=proto_dot_proxy__service__pb2.ScrapeRequest.SerializeToString,
        ),
        'writeResponses': grpc.stream_unary_rpc_method_handler(
            servicer.writeResponses,
            request_deserializer=proto_dot_proxy__service__pb2.ScrapeResult.FromString,
            response_serializer=proto_dot_proxy__service__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'proxy_service.ProxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
